"""Prompt templates and rubrics for hierarchical verification agents."""

import json


def build_orchestrator_prompt(
    *,
    requirements_list: list[str],
    file_analyses: list[dict[str, object]],
) -> str:
    """Build prompt for the orchestrator to dynamically spawn sub-agents.

    Args:
        requirements_list: List of all requirements
        file_analyses: Objective descriptions of the files

    Returns:
        Prompt for strict JSON sub-task generation
    """
    context = {
        "requirements_list": requirements_list,
        "file_analyses": file_analyses,
    }
    return (
        "You are an Orchestrator Agent for a Hierarchical Verification System. "
        "Your job is to read the file analyses and the user's requirements, "
        "and conceptually group the requirements into logical domains. "
        "For each domain, spawn a specialized Sub-Agent to perform the check.\n\n"
        "Rules:\n"
        "1. Every requirement MUST be assigned to exactly one Sub-Agent.\n"
        "2. Name the agents professionally (e.g., 'SecurityAuditor', 'DesignReviewer').\n"
        "3. Keep the number of agents efficient (1-4 max).\n\n"
        "Return strict JSON with keys:\n"
        "  tasks: list of objects with keys: "
        "    agent_name (string)\n"
        "    focus_area (string brief summary of what it checks)\n"
        "    assigned_requirements (list of string exact requirements)\n\n"
        f"Context JSON: {json.dumps(context, ensure_ascii=True)}"
    )


def build_specialized_agent_prompt(
    *,
    agent_name: str,
    focus_area: str,
    assigned_requirements: list[str],
    file_analyses: list[dict[str, object]],
    seller_profile: str,
    what_they_offer: str,
) -> str:
    """Build prompt for a dynamically spawned specialized agent.

    Args:
        agent_name: Name of the agent generated by orchestrator
        focus_area: Area of focus generated by orchestrator
        assigned_requirements: Specific requirements to check
        file_analyses: Evidence
        seller_profile: Seller context
        what_they_offer: Offer context

    Returns:
        Prompt for specialized checking
    """
    context = {
        "assigned_requirements": assigned_requirements,
        "file_analyses": file_analyses,
        "seller_profile": seller_profile,
        "what_they_offer": what_they_offer,
    }
    return (
        f"You are a specialized verification agent named '{agent_name}'. "
        f"Your focus area is: {focus_area}.\n\n"
        "You have received objective content analyses of uploaded files. "
        "Your job is to check YOUR SPECIFIC assigned requirements strictly against "
        "the content analysis evidence.\n\n"
        "CRITICAL RULES:\n"
        "- A requirement is ONLY 'checked: true' if the evidence supports it.\n"
        "- Do not evaluate requirements outside your assigned list.\n"
        "- Seller marketing claims are not valid evidence for objective checks.\n\n"
        "Return strict JSON with keys:\n"
        "  requirement_checks: list of objects with keys: "
        "requirement, checked (bool), evidence (string justification)\n\n"
        f"Context JSON: {json.dumps(context, ensure_ascii=True)}"
    )
